# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: class_label_translation.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("class_label_translation.proto", :syntax => :proto3) do
    add_message "ClassLabelTranslation.ClassLabelTranslation" do
      map :to_numeric, :string, :int32, 1
      map :class_count, :string, :uint32, 2
    end
  end
end

module ClassLabelTranslation
  ClassLabelTranslation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ClassLabelTranslation.ClassLabelTranslation").msgclass
end
