# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: feature_scaling.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("feature_scaling.proto", :syntax => :proto3) do
    add_message "FeatureScaling.FeatureScaling" do
      proto3_optional :min, :double, 1
      proto3_optional :max, :double, 2
      proto3_optional :nsamples, :uint32, 3
      proto3_optional :mean, :double, 4
    end
  end
end

module FeatureScaling
  FeatureScaling = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FeatureScaling.FeatureScaling").msgclass
end
