# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gfp_model.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("gfp_model.proto", :syntax => :proto3) do
    add_message "GfpModel.ModelMetadata" do
      proto3_optional :response_name, :string, 1
      proto3_optional :fingerprints, :string, 2
      proto3_optional :class_label_translation, :string, 3
      proto3_optional :response_scaling, :string, 4
      proto3_optional :flatten_sparse_fingerprints, :bool, 5
      proto3_optional :date_built, :string, 6
    end
    add_message "GfpModel.SvmfpModel" do
      optional :metadata, :message, 1, "GfpModel.ModelMetadata"
      proto3_optional :bit_subset, :string, 2
      proto3_optional :bit_xref, :string, 3
      proto3_optional :train_gfp, :string, 4
      proto3_optional :support_vectors, :string, 5
      proto3_optional :threshold_b, :double, 6
    end
    add_message "GfpModel.LightGbmModel" do
      optional :metadata, :message, 1, "GfpModel.ModelMetadata"
      proto3_optional :bit_xref, :string, 4
    end
    add_message "GfpModel.CatboostModel" do
      optional :metadata, :message, 1, "GfpModel.ModelMetadata"
      proto3_optional :bit_xref, :string, 4
    end
  end
end

module GfpModel
  ModelMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GfpModel.ModelMetadata").msgclass
  SvmfpModel = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GfpModel.SvmfpModel").msgclass
  LightGbmModel = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GfpModel.LightGbmModel").msgclass
  CatboostModel = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GfpModel.CatboostModel").msgclass
end
