# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gfp_to_svm_lite.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("gfp_to_svm_lite.proto", :syntax => :proto3) do
    add_message "GfpBitSubset.BitSubset" do
      proto3_optional :fp_name, :string, 1
      repeated :bits, :uint32, 2
    end
    add_message "GfpBitSubset.BitXref" do
      proto3_optional :fp_name, :string, 1
      map :bit_to_feature, :uint32, :uint32, 2
    end
    add_message "GfpBitSubset.Params" do
      proto3_optional :support, :uint32, 1
      proto3_optional :flatten_sparse_fingerprints, :bool, 2
      proto3_optional :highest_feature_number, :uint32, 3
    end
    add_message "GfpBitSubset.GfpBitSubset" do
      map :xref, :string, :message, 1, "GfpBitSubset.BitSubset"
      optional :params, :message, 2, "GfpBitSubset.Params"
    end
    add_message "GfpBitSubset.GfpBitToFeature" do
      map :xref, :string, :message, 1, "GfpBitSubset.BitXref"
      optional :params, :message, 2, "GfpBitSubset.Params"
    end
  end
end

module GfpBitSubset
  BitSubset = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GfpBitSubset.BitSubset").msgclass
  BitXref = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GfpBitSubset.BitXref").msgclass
  Params = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GfpBitSubset.Params").msgclass
  GfpBitSubset = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GfpBitSubset.GfpBitSubset").msgclass
  GfpBitToFeature = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GfpBitSubset.GfpBitToFeature").msgclass
end
