# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: svm_lite_model.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("svm_lite_model.proto", :syntax => :proto3) do
    add_message "SvmLiteModel.FeatureCount" do
      optional :feature_number, :uint32, 1
      optional :count, :uint32, 2
    end
    add_message "SvmLiteModel.SupportVector" do
      optional :weight, :double, 1
      repeated :feature, :message, 2, "SvmLiteModel.FeatureCount"
      proto3_optional :id, :string, 3
    end
    add_message "SvmLiteModel.SvmLiteModel" do
      proto3_optional :kernel_type, :int32, 1
      repeated :kernel_parameter, :int32, 2
      proto3_optional :dash_u, :double, 3
      proto3_optional :number_training_documents, :int32, 4
      proto3_optional :threshold_b, :double, 5
      repeated :support_vector, :message, 6, "SvmLiteModel.SupportVector"
    end
  end
end

module SvmLiteModel
  FeatureCount = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SvmLiteModel.FeatureCount").msgclass
  SupportVector = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SvmLiteModel.SupportVector").msgclass
  SvmLiteModel = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SvmLiteModel.SvmLiteModel").msgclass
end
