# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: svmfp_model.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("svmfp_model.proto", :syntax => :proto3) do
    add_message "SvmfpModel.SvmfpModel" do
      proto3_optional :response_name, :string, 1
      proto3_optional :fingerprints, :string, 2
      proto3_optional :bit_xref, :string, 3
      proto3_optional :support_vectors, :string, 4
      proto3_optional :threshold_b, :double, 5
      proto3_optional :class_label_translation, :string, 6
      proto3_optional :date_built, :string, 7
    end
  end
end

module SvmfpModel
  SvmfpModel = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SvmfpModel.SvmfpModel").msgclass
end
