cc_library(
    name = "cmdline_v2",
    visibility = ["//visibility:public"],
    srcs = [
        "cmdline.cc",
    ],
    hdrs = [
        "cmdline_v2.h",
    ],
    deps = [
        "//Foundational/iwaray:iwaray",
        "//Foundational/iwmisc:iwmisc",
        "//Foundational/iwstring:iwstring",
    ],

)
