# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Molecule_Lib/geometric_constraints.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("Molecule_Lib/geometric_constraints.proto", :syntax => :proto3) do
    add_message "GeometricConstraints.Range" do
      optional :min, :float, 1
      optional :max, :float, 2
    end
    add_message "GeometricConstraints.Distance" do
      optional :a1, :int32, 1
      optional :a2, :int32, 2
      optional :range, :message, 3, "GeometricConstraints.Range"
    end
    add_message "GeometricConstraints.BondAngle" do
      optional :a1, :uint32, 1
      optional :a2, :uint32, 2
      optional :a3, :uint32, 3
      optional :range, :message, 4, "GeometricConstraints.Range"
    end
    add_message "GeometricConstraints.TorsionAngle" do
      optional :a1, :uint32, 1
      optional :a2, :uint32, 2
      optional :a3, :uint32, 3
      optional :a4, :uint32, 4
      optional :range, :message, 5, "GeometricConstraints.Range"
    end
    add_message "GeometricConstraints.SetOfConstraints" do
      repeated :distances, :message, 1, "GeometricConstraints.Distance"
      repeated :bond_angles, :message, 2, "GeometricConstraints.BondAngle"
      repeated :torsion_angles, :message, 3, "GeometricConstraints.TorsionAngle"
      optional :number_to_match, :uint32, 4
    end
  end
end

module GeometricConstraints
  Range = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GeometricConstraints.Range").msgclass
  Distance = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GeometricConstraints.Distance").msgclass
  BondAngle = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GeometricConstraints.BondAngle").msgclass
  TorsionAngle = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GeometricConstraints.TorsionAngle").msgclass
  SetOfConstraints = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GeometricConstraints.SetOfConstraints").msgclass
end
