# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Molecule_Lib/geometric_constraints.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(Molecule_Lib/geometric_constraints.proto\x12\x14GeometricConstraints\"!\n\x05Range\x12\x0b\n\x03min\x18\x01 \x01(\x02\x12\x0b\n\x03max\x18\x02 \x01(\x02\"N\n\x08\x44istance\x12\n\n\x02\x61\x31\x18\x01 \x01(\x05\x12\n\n\x02\x61\x32\x18\x02 \x01(\x05\x12*\n\x05range\x18\x03 \x01(\x0b\x32\x1b.GeometricConstraints.Range\"[\n\tBondAngle\x12\n\n\x02\x61\x31\x18\x01 \x01(\r\x12\n\n\x02\x61\x32\x18\x02 \x01(\r\x12\n\n\x02\x61\x33\x18\x03 \x01(\r\x12*\n\x05range\x18\x04 \x01(\x0b\x32\x1b.GeometricConstraints.Range\"j\n\x0cTorsionAngle\x12\n\n\x02\x61\x31\x18\x01 \x01(\r\x12\n\n\x02\x61\x32\x18\x02 \x01(\r\x12\n\n\x02\x61\x33\x18\x03 \x01(\r\x12\n\n\x02\x61\x34\x18\x04 \x01(\r\x12*\n\x05range\x18\x05 \x01(\x0b\x32\x1b.GeometricConstraints.Range\"\xd0\x01\n\x10SetOfConstraints\x12\x31\n\tdistances\x18\x01 \x03(\x0b\x32\x1e.GeometricConstraints.Distance\x12\x34\n\x0b\x62ond_angles\x18\x02 \x03(\x0b\x32\x1f.GeometricConstraints.BondAngle\x12:\n\x0etorsion_angles\x18\x03 \x03(\x0b\x32\".GeometricConstraints.TorsionAngle\x12\x17\n\x0fnumber_to_match\x18\x04 \x01(\rb\x06proto3')



_RANGE = DESCRIPTOR.message_types_by_name['Range']
_DISTANCE = DESCRIPTOR.message_types_by_name['Distance']
_BONDANGLE = DESCRIPTOR.message_types_by_name['BondAngle']
_TORSIONANGLE = DESCRIPTOR.message_types_by_name['TorsionAngle']
_SETOFCONSTRAINTS = DESCRIPTOR.message_types_by_name['SetOfConstraints']
Range = _reflection.GeneratedProtocolMessageType('Range', (_message.Message,), {
  'DESCRIPTOR' : _RANGE,
  '__module__' : 'Molecule_Lib.geometric_constraints_pb2'
  # @@protoc_insertion_point(class_scope:GeometricConstraints.Range)
  })
_sym_db.RegisterMessage(Range)

Distance = _reflection.GeneratedProtocolMessageType('Distance', (_message.Message,), {
  'DESCRIPTOR' : _DISTANCE,
  '__module__' : 'Molecule_Lib.geometric_constraints_pb2'
  # @@protoc_insertion_point(class_scope:GeometricConstraints.Distance)
  })
_sym_db.RegisterMessage(Distance)

BondAngle = _reflection.GeneratedProtocolMessageType('BondAngle', (_message.Message,), {
  'DESCRIPTOR' : _BONDANGLE,
  '__module__' : 'Molecule_Lib.geometric_constraints_pb2'
  # @@protoc_insertion_point(class_scope:GeometricConstraints.BondAngle)
  })
_sym_db.RegisterMessage(BondAngle)

TorsionAngle = _reflection.GeneratedProtocolMessageType('TorsionAngle', (_message.Message,), {
  'DESCRIPTOR' : _TORSIONANGLE,
  '__module__' : 'Molecule_Lib.geometric_constraints_pb2'
  # @@protoc_insertion_point(class_scope:GeometricConstraints.TorsionAngle)
  })
_sym_db.RegisterMessage(TorsionAngle)

SetOfConstraints = _reflection.GeneratedProtocolMessageType('SetOfConstraints', (_message.Message,), {
  'DESCRIPTOR' : _SETOFCONSTRAINTS,
  '__module__' : 'Molecule_Lib.geometric_constraints_pb2'
  # @@protoc_insertion_point(class_scope:GeometricConstraints.SetOfConstraints)
  })
_sym_db.RegisterMessage(SetOfConstraints)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RANGE._serialized_start=66
  _RANGE._serialized_end=99
  _DISTANCE._serialized_start=101
  _DISTANCE._serialized_end=179
  _BONDANGLE._serialized_start=181
  _BONDANGLE._serialized_end=272
  _TORSIONANGLE._serialized_start=274
  _TORSIONANGLE._serialized_end=380
  _SETOFCONSTRAINTS._serialized_start=383
  _SETOFCONSTRAINTS._serialized_end=591
# @@protoc_insertion_point(module_scope)
