# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: class_label_translation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='class_label_translation.proto',
  package='ClassLabelTranslation',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1d\x63lass_label_translation.proto\x12\x15\x43lassLabelTranslation\"\xa0\x02\n\x15\x43lassLabelTranslation\x12O\n\nto_numeric\x18\x01 \x03(\x0b\x32;.ClassLabelTranslation.ClassLabelTranslation.ToNumericEntry\x12Q\n\x0b\x63lass_count\x18\x02 \x03(\x0b\x32<.ClassLabelTranslation.ClassLabelTranslation.ClassCountEntry\x1a\x30\n\x0eToNumericEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a\x31\n\x0f\x43lassCountEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x62\x06proto3'
)




_CLASSLABELTRANSLATION_TONUMERICENTRY = _descriptor.Descriptor(
  name='ToNumericEntry',
  full_name='ClassLabelTranslation.ClassLabelTranslation.ToNumericEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ClassLabelTranslation.ClassLabelTranslation.ToNumericEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='ClassLabelTranslation.ClassLabelTranslation.ToNumericEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=294,
)

_CLASSLABELTRANSLATION_CLASSCOUNTENTRY = _descriptor.Descriptor(
  name='ClassCountEntry',
  full_name='ClassLabelTranslation.ClassLabelTranslation.ClassCountEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ClassLabelTranslation.ClassLabelTranslation.ClassCountEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='ClassLabelTranslation.ClassLabelTranslation.ClassCountEntry.value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=296,
  serialized_end=345,
)

_CLASSLABELTRANSLATION = _descriptor.Descriptor(
  name='ClassLabelTranslation',
  full_name='ClassLabelTranslation.ClassLabelTranslation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='to_numeric', full_name='ClassLabelTranslation.ClassLabelTranslation.to_numeric', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='class_count', full_name='ClassLabelTranslation.ClassLabelTranslation.class_count', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CLASSLABELTRANSLATION_TONUMERICENTRY, _CLASSLABELTRANSLATION_CLASSCOUNTENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=345,
)

_CLASSLABELTRANSLATION_TONUMERICENTRY.containing_type = _CLASSLABELTRANSLATION
_CLASSLABELTRANSLATION_CLASSCOUNTENTRY.containing_type = _CLASSLABELTRANSLATION
_CLASSLABELTRANSLATION.fields_by_name['to_numeric'].message_type = _CLASSLABELTRANSLATION_TONUMERICENTRY
_CLASSLABELTRANSLATION.fields_by_name['class_count'].message_type = _CLASSLABELTRANSLATION_CLASSCOUNTENTRY
DESCRIPTOR.message_types_by_name['ClassLabelTranslation'] = _CLASSLABELTRANSLATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClassLabelTranslation = _reflection.GeneratedProtocolMessageType('ClassLabelTranslation', (_message.Message,), {

  'ToNumericEntry' : _reflection.GeneratedProtocolMessageType('ToNumericEntry', (_message.Message,), {
    'DESCRIPTOR' : _CLASSLABELTRANSLATION_TONUMERICENTRY,
    '__module__' : 'class_label_translation_pb2'
    # @@protoc_insertion_point(class_scope:ClassLabelTranslation.ClassLabelTranslation.ToNumericEntry)
    })
  ,

  'ClassCountEntry' : _reflection.GeneratedProtocolMessageType('ClassCountEntry', (_message.Message,), {
    'DESCRIPTOR' : _CLASSLABELTRANSLATION_CLASSCOUNTENTRY,
    '__module__' : 'class_label_translation_pb2'
    # @@protoc_insertion_point(class_scope:ClassLabelTranslation.ClassLabelTranslation.ClassCountEntry)
    })
  ,
  'DESCRIPTOR' : _CLASSLABELTRANSLATION,
  '__module__' : 'class_label_translation_pb2'
  # @@protoc_insertion_point(class_scope:ClassLabelTranslation.ClassLabelTranslation)
  })
_sym_db.RegisterMessage(ClassLabelTranslation)
_sym_db.RegisterMessage(ClassLabelTranslation.ToNumericEntry)
_sym_db.RegisterMessage(ClassLabelTranslation.ClassCountEntry)


_CLASSLABELTRANSLATION_TONUMERICENTRY._options = None
_CLASSLABELTRANSLATION_CLASSCOUNTENTRY._options = None
# @@protoc_insertion_point(module_scope)
