# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Utilities/GFP_Tools/gfp_to_svm_lite.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)Utilities/GFP_Tools/gfp_to_svm_lite.proto\x12\x0cGfpBitSubset\".\n\tBitSubset\x12\x0f\n\x07\x66p_name\x18\x01 \x01(\t\x12\x10\n\x04\x62its\x18\x02 \x03(\rB\x02\x10\x01\"\x90\x01\n\x07\x42itXref\x12\x0f\n\x07\x66p_name\x18\x01 \x01(\t\x12?\n\x0e\x62it_to_feature\x18\x02 \x03(\x0b\x32\'.GfpBitSubset.BitXref.BitToFeatureEntry\x1a\x33\n\x11\x42itToFeatureEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\"^\n\x06Params\x12\x0f\n\x07support\x18\x01 \x01(\r\x12#\n\x1b\x66latten_sparse_fingerprints\x18\x02 \x01(\x08\x12\x1e\n\x16highest_feature_number\x18\x03 \x01(\r\"\xae\x01\n\x0cGfpBitSubset\x12\x32\n\x04xref\x18\x01 \x03(\x0b\x32$.GfpBitSubset.GfpBitSubset.XrefEntry\x12$\n\x06params\x18\x02 \x01(\x0b\x32\x14.GfpBitSubset.Params\x1a\x44\n\tXrefEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.GfpBitSubset.BitSubset:\x02\x38\x01\"\xb2\x01\n\x0fGfpBitToFeature\x12\x35\n\x04xref\x18\x01 \x03(\x0b\x32\'.GfpBitSubset.GfpBitToFeature.XrefEntry\x12$\n\x06params\x18\x02 \x01(\x0b\x32\x14.GfpBitSubset.Params\x1a\x42\n\tXrefEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.GfpBitSubset.BitXref:\x02\x38\x01\x62\x06proto3')



_BITSUBSET = DESCRIPTOR.message_types_by_name['BitSubset']
_BITXREF = DESCRIPTOR.message_types_by_name['BitXref']
_BITXREF_BITTOFEATUREENTRY = _BITXREF.nested_types_by_name['BitToFeatureEntry']
_PARAMS = DESCRIPTOR.message_types_by_name['Params']
_GFPBITSUBSET = DESCRIPTOR.message_types_by_name['GfpBitSubset']
_GFPBITSUBSET_XREFENTRY = _GFPBITSUBSET.nested_types_by_name['XrefEntry']
_GFPBITTOFEATURE = DESCRIPTOR.message_types_by_name['GfpBitToFeature']
_GFPBITTOFEATURE_XREFENTRY = _GFPBITTOFEATURE.nested_types_by_name['XrefEntry']
BitSubset = _reflection.GeneratedProtocolMessageType('BitSubset', (_message.Message,), {
  'DESCRIPTOR' : _BITSUBSET,
  '__module__' : 'Utilities.GFP_Tools.gfp_to_svm_lite_pb2'
  # @@protoc_insertion_point(class_scope:GfpBitSubset.BitSubset)
  })
_sym_db.RegisterMessage(BitSubset)

BitXref = _reflection.GeneratedProtocolMessageType('BitXref', (_message.Message,), {

  'BitToFeatureEntry' : _reflection.GeneratedProtocolMessageType('BitToFeatureEntry', (_message.Message,), {
    'DESCRIPTOR' : _BITXREF_BITTOFEATUREENTRY,
    '__module__' : 'Utilities.GFP_Tools.gfp_to_svm_lite_pb2'
    # @@protoc_insertion_point(class_scope:GfpBitSubset.BitXref.BitToFeatureEntry)
    })
  ,
  'DESCRIPTOR' : _BITXREF,
  '__module__' : 'Utilities.GFP_Tools.gfp_to_svm_lite_pb2'
  # @@protoc_insertion_point(class_scope:GfpBitSubset.BitXref)
  })
_sym_db.RegisterMessage(BitXref)
_sym_db.RegisterMessage(BitXref.BitToFeatureEntry)

Params = _reflection.GeneratedProtocolMessageType('Params', (_message.Message,), {
  'DESCRIPTOR' : _PARAMS,
  '__module__' : 'Utilities.GFP_Tools.gfp_to_svm_lite_pb2'
  # @@protoc_insertion_point(class_scope:GfpBitSubset.Params)
  })
_sym_db.RegisterMessage(Params)

GfpBitSubset = _reflection.GeneratedProtocolMessageType('GfpBitSubset', (_message.Message,), {

  'XrefEntry' : _reflection.GeneratedProtocolMessageType('XrefEntry', (_message.Message,), {
    'DESCRIPTOR' : _GFPBITSUBSET_XREFENTRY,
    '__module__' : 'Utilities.GFP_Tools.gfp_to_svm_lite_pb2'
    # @@protoc_insertion_point(class_scope:GfpBitSubset.GfpBitSubset.XrefEntry)
    })
  ,
  'DESCRIPTOR' : _GFPBITSUBSET,
  '__module__' : 'Utilities.GFP_Tools.gfp_to_svm_lite_pb2'
  # @@protoc_insertion_point(class_scope:GfpBitSubset.GfpBitSubset)
  })
_sym_db.RegisterMessage(GfpBitSubset)
_sym_db.RegisterMessage(GfpBitSubset.XrefEntry)

GfpBitToFeature = _reflection.GeneratedProtocolMessageType('GfpBitToFeature', (_message.Message,), {

  'XrefEntry' : _reflection.GeneratedProtocolMessageType('XrefEntry', (_message.Message,), {
    'DESCRIPTOR' : _GFPBITTOFEATURE_XREFENTRY,
    '__module__' : 'Utilities.GFP_Tools.gfp_to_svm_lite_pb2'
    # @@protoc_insertion_point(class_scope:GfpBitSubset.GfpBitToFeature.XrefEntry)
    })
  ,
  'DESCRIPTOR' : _GFPBITTOFEATURE,
  '__module__' : 'Utilities.GFP_Tools.gfp_to_svm_lite_pb2'
  # @@protoc_insertion_point(class_scope:GfpBitSubset.GfpBitToFeature)
  })
_sym_db.RegisterMessage(GfpBitToFeature)
_sym_db.RegisterMessage(GfpBitToFeature.XrefEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BITSUBSET.fields_by_name['bits']._options = None
  _BITSUBSET.fields_by_name['bits']._serialized_options = b'\020\001'
  _BITXREF_BITTOFEATUREENTRY._options = None
  _BITXREF_BITTOFEATUREENTRY._serialized_options = b'8\001'
  _GFPBITSUBSET_XREFENTRY._options = None
  _GFPBITSUBSET_XREFENTRY._serialized_options = b'8\001'
  _GFPBITTOFEATURE_XREFENTRY._options = None
  _GFPBITTOFEATURE_XREFENTRY._serialized_options = b'8\001'
  _BITSUBSET._serialized_start=59
  _BITSUBSET._serialized_end=105
  _BITXREF._serialized_start=108
  _BITXREF._serialized_end=252
  _BITXREF_BITTOFEATUREENTRY._serialized_start=201
  _BITXREF_BITTOFEATUREENTRY._serialized_end=252
  _PARAMS._serialized_start=254
  _PARAMS._serialized_end=348
  _GFPBITSUBSET._serialized_start=351
  _GFPBITSUBSET._serialized_end=525
  _GFPBITSUBSET_XREFENTRY._serialized_start=457
  _GFPBITSUBSET_XREFENTRY._serialized_end=525
  _GFPBITTOFEATURE._serialized_start=528
  _GFPBITTOFEATURE._serialized_end=706
  _GFPBITTOFEATURE_XREFENTRY._serialized_start=640
  _GFPBITTOFEATURE_XREFENTRY._serialized_end=706
# @@protoc_insertion_point(module_scope)
