# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Utilities/GFP_Tools/gfp_model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#Utilities/GFP_Tools/gfp_model.proto\x12\x08GfpModel\"\xb0\x01\n\rModelMetadata\x12\x15\n\rresponse_name\x18\x01 \x01(\t\x12\x14\n\x0c\x66ingerprints\x18\x02 \x01(\t\x12\x1f\n\x17\x63lass_label_translation\x18\x03 \x01(\t\x12\x18\n\x10response_scaling\x18\x04 \x01(\t\x12#\n\x1b\x66latten_sparse_fingerprints\x18\x05 \x01(\x08\x12\x12\n\ndate_built\x18\x06 \x01(\t\"\x9e\x01\n\nSvmfpModel\x12)\n\x08metadata\x18\x01 \x01(\x0b\x32\x17.GfpModel.ModelMetadata\x12\x12\n\nbit_subset\x18\x02 \x01(\t\x12\x10\n\x08\x62it_xref\x18\x03 \x01(\t\x12\x11\n\ttrain_gfp\x18\x04 \x01(\t\x12\x17\n\x0fsupport_vectors\x18\x05 \x01(\t\x12\x13\n\x0bthreshold_b\x18\x06 \x01(\x01\"L\n\rLightGbmModel\x12)\n\x08metadata\x18\x01 \x01(\x0b\x32\x17.GfpModel.ModelMetadata\x12\x10\n\x08\x62it_xref\x18\x04 \x01(\t\"L\n\rCatboostModel\x12)\n\x08metadata\x18\x01 \x01(\x0b\x32\x17.GfpModel.ModelMetadata\x12\x10\n\x08\x62it_xref\x18\x04 \x01(\tb\x06proto3')



_MODELMETADATA = DESCRIPTOR.message_types_by_name['ModelMetadata']
_SVMFPMODEL = DESCRIPTOR.message_types_by_name['SvmfpModel']
_LIGHTGBMMODEL = DESCRIPTOR.message_types_by_name['LightGbmModel']
_CATBOOSTMODEL = DESCRIPTOR.message_types_by_name['CatboostModel']
ModelMetadata = _reflection.GeneratedProtocolMessageType('ModelMetadata', (_message.Message,), {
  'DESCRIPTOR' : _MODELMETADATA,
  '__module__' : 'Utilities.GFP_Tools.gfp_model_pb2'
  # @@protoc_insertion_point(class_scope:GfpModel.ModelMetadata)
  })
_sym_db.RegisterMessage(ModelMetadata)

SvmfpModel = _reflection.GeneratedProtocolMessageType('SvmfpModel', (_message.Message,), {
  'DESCRIPTOR' : _SVMFPMODEL,
  '__module__' : 'Utilities.GFP_Tools.gfp_model_pb2'
  # @@protoc_insertion_point(class_scope:GfpModel.SvmfpModel)
  })
_sym_db.RegisterMessage(SvmfpModel)

LightGbmModel = _reflection.GeneratedProtocolMessageType('LightGbmModel', (_message.Message,), {
  'DESCRIPTOR' : _LIGHTGBMMODEL,
  '__module__' : 'Utilities.GFP_Tools.gfp_model_pb2'
  # @@protoc_insertion_point(class_scope:GfpModel.LightGbmModel)
  })
_sym_db.RegisterMessage(LightGbmModel)

CatboostModel = _reflection.GeneratedProtocolMessageType('CatboostModel', (_message.Message,), {
  'DESCRIPTOR' : _CATBOOSTMODEL,
  '__module__' : 'Utilities.GFP_Tools.gfp_model_pb2'
  # @@protoc_insertion_point(class_scope:GfpModel.CatboostModel)
  })
_sym_db.RegisterMessage(CatboostModel)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MODELMETADATA._serialized_start=50
  _MODELMETADATA._serialized_end=226
  _SVMFPMODEL._serialized_start=229
  _SVMFPMODEL._serialized_end=387
  _LIGHTGBMMODEL._serialized_start=389
  _LIGHTGBMMODEL._serialized_end=465
  _CATBOOSTMODEL._serialized_start=467
  _CATBOOSTMODEL._serialized_end=543
# @@protoc_insertion_point(module_scope)
