# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gfp_model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gfp_model.proto',
  package='GfpModel',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fgfp_model.proto\x12\x08GfpModel\"\xd1\x02\n\rModelMetadata\x12\x1a\n\rresponse_name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x19\n\x0c\x66ingerprints\x18\x02 \x01(\tH\x01\x88\x01\x01\x12$\n\x17\x63lass_label_translation\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x1d\n\x10response_scaling\x18\x04 \x01(\tH\x03\x88\x01\x01\x12(\n\x1b\x66latten_sparse_fingerprints\x18\x05 \x01(\x08H\x04\x88\x01\x01\x12\x17\n\ndate_built\x18\x06 \x01(\tH\x05\x88\x01\x01\x42\x10\n\x0e_response_nameB\x0f\n\r_fingerprintsB\x1a\n\x18_class_label_translationB\x13\n\x11_response_scalingB\x1e\n\x1c_flatten_sparse_fingerprintsB\r\n\x0b_date_built\"\x85\x02\n\nSvmfpModel\x12)\n\x08metadata\x18\x01 \x01(\x0b\x32\x17.GfpModel.ModelMetadata\x12\x17\n\nbit_subset\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08\x62it_xref\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x16\n\ttrain_gfp\x18\x04 \x01(\tH\x02\x88\x01\x01\x12\x1c\n\x0fsupport_vectors\x18\x05 \x01(\tH\x03\x88\x01\x01\x12\x18\n\x0bthreshold_b\x18\x06 \x01(\x01H\x04\x88\x01\x01\x42\r\n\x0b_bit_subsetB\x0b\n\t_bit_xrefB\x0c\n\n_train_gfpB\x12\n\x10_support_vectorsB\x0e\n\x0c_threshold_b\"^\n\rLightGbmModel\x12)\n\x08metadata\x18\x01 \x01(\x0b\x32\x17.GfpModel.ModelMetadata\x12\x15\n\x08\x62it_xref\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_bit_xrefb\x06proto3'
)




_MODELMETADATA = _descriptor.Descriptor(
  name='ModelMetadata',
  full_name='GfpModel.ModelMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response_name', full_name='GfpModel.ModelMetadata.response_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fingerprints', full_name='GfpModel.ModelMetadata.fingerprints', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='class_label_translation', full_name='GfpModel.ModelMetadata.class_label_translation', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response_scaling', full_name='GfpModel.ModelMetadata.response_scaling', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flatten_sparse_fingerprints', full_name='GfpModel.ModelMetadata.flatten_sparse_fingerprints', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date_built', full_name='GfpModel.ModelMetadata.date_built', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_response_name', full_name='GfpModel.ModelMetadata._response_name',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_fingerprints', full_name='GfpModel.ModelMetadata._fingerprints',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_class_label_translation', full_name='GfpModel.ModelMetadata._class_label_translation',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_response_scaling', full_name='GfpModel.ModelMetadata._response_scaling',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_flatten_sparse_fingerprints', full_name='GfpModel.ModelMetadata._flatten_sparse_fingerprints',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_date_built', full_name='GfpModel.ModelMetadata._date_built',
      index=5, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=30,
  serialized_end=367,
)


_SVMFPMODEL = _descriptor.Descriptor(
  name='SvmfpModel',
  full_name='GfpModel.SvmfpModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='metadata', full_name='GfpModel.SvmfpModel.metadata', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bit_subset', full_name='GfpModel.SvmfpModel.bit_subset', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bit_xref', full_name='GfpModel.SvmfpModel.bit_xref', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='train_gfp', full_name='GfpModel.SvmfpModel.train_gfp', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='support_vectors', full_name='GfpModel.SvmfpModel.support_vectors', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='threshold_b', full_name='GfpModel.SvmfpModel.threshold_b', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_bit_subset', full_name='GfpModel.SvmfpModel._bit_subset',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_bit_xref', full_name='GfpModel.SvmfpModel._bit_xref',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_train_gfp', full_name='GfpModel.SvmfpModel._train_gfp',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_support_vectors', full_name='GfpModel.SvmfpModel._support_vectors',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_threshold_b', full_name='GfpModel.SvmfpModel._threshold_b',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=370,
  serialized_end=631,
)


_LIGHTGBMMODEL = _descriptor.Descriptor(
  name='LightGbmModel',
  full_name='GfpModel.LightGbmModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='metadata', full_name='GfpModel.LightGbmModel.metadata', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bit_xref', full_name='GfpModel.LightGbmModel.bit_xref', index=1,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_bit_xref', full_name='GfpModel.LightGbmModel._bit_xref',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=633,
  serialized_end=727,
)

_MODELMETADATA.oneofs_by_name['_response_name'].fields.append(
  _MODELMETADATA.fields_by_name['response_name'])
_MODELMETADATA.fields_by_name['response_name'].containing_oneof = _MODELMETADATA.oneofs_by_name['_response_name']
_MODELMETADATA.oneofs_by_name['_fingerprints'].fields.append(
  _MODELMETADATA.fields_by_name['fingerprints'])
_MODELMETADATA.fields_by_name['fingerprints'].containing_oneof = _MODELMETADATA.oneofs_by_name['_fingerprints']
_MODELMETADATA.oneofs_by_name['_class_label_translation'].fields.append(
  _MODELMETADATA.fields_by_name['class_label_translation'])
_MODELMETADATA.fields_by_name['class_label_translation'].containing_oneof = _MODELMETADATA.oneofs_by_name['_class_label_translation']
_MODELMETADATA.oneofs_by_name['_response_scaling'].fields.append(
  _MODELMETADATA.fields_by_name['response_scaling'])
_MODELMETADATA.fields_by_name['response_scaling'].containing_oneof = _MODELMETADATA.oneofs_by_name['_response_scaling']
_MODELMETADATA.oneofs_by_name['_flatten_sparse_fingerprints'].fields.append(
  _MODELMETADATA.fields_by_name['flatten_sparse_fingerprints'])
_MODELMETADATA.fields_by_name['flatten_sparse_fingerprints'].containing_oneof = _MODELMETADATA.oneofs_by_name['_flatten_sparse_fingerprints']
_MODELMETADATA.oneofs_by_name['_date_built'].fields.append(
  _MODELMETADATA.fields_by_name['date_built'])
_MODELMETADATA.fields_by_name['date_built'].containing_oneof = _MODELMETADATA.oneofs_by_name['_date_built']
_SVMFPMODEL.fields_by_name['metadata'].message_type = _MODELMETADATA
_SVMFPMODEL.oneofs_by_name['_bit_subset'].fields.append(
  _SVMFPMODEL.fields_by_name['bit_subset'])
_SVMFPMODEL.fields_by_name['bit_subset'].containing_oneof = _SVMFPMODEL.oneofs_by_name['_bit_subset']
_SVMFPMODEL.oneofs_by_name['_bit_xref'].fields.append(
  _SVMFPMODEL.fields_by_name['bit_xref'])
_SVMFPMODEL.fields_by_name['bit_xref'].containing_oneof = _SVMFPMODEL.oneofs_by_name['_bit_xref']
_SVMFPMODEL.oneofs_by_name['_train_gfp'].fields.append(
  _SVMFPMODEL.fields_by_name['train_gfp'])
_SVMFPMODEL.fields_by_name['train_gfp'].containing_oneof = _SVMFPMODEL.oneofs_by_name['_train_gfp']
_SVMFPMODEL.oneofs_by_name['_support_vectors'].fields.append(
  _SVMFPMODEL.fields_by_name['support_vectors'])
_SVMFPMODEL.fields_by_name['support_vectors'].containing_oneof = _SVMFPMODEL.oneofs_by_name['_support_vectors']
_SVMFPMODEL.oneofs_by_name['_threshold_b'].fields.append(
  _SVMFPMODEL.fields_by_name['threshold_b'])
_SVMFPMODEL.fields_by_name['threshold_b'].containing_oneof = _SVMFPMODEL.oneofs_by_name['_threshold_b']
_LIGHTGBMMODEL.fields_by_name['metadata'].message_type = _MODELMETADATA
_LIGHTGBMMODEL.oneofs_by_name['_bit_xref'].fields.append(
  _LIGHTGBMMODEL.fields_by_name['bit_xref'])
_LIGHTGBMMODEL.fields_by_name['bit_xref'].containing_oneof = _LIGHTGBMMODEL.oneofs_by_name['_bit_xref']
DESCRIPTOR.message_types_by_name['ModelMetadata'] = _MODELMETADATA
DESCRIPTOR.message_types_by_name['SvmfpModel'] = _SVMFPMODEL
DESCRIPTOR.message_types_by_name['LightGbmModel'] = _LIGHTGBMMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelMetadata = _reflection.GeneratedProtocolMessageType('ModelMetadata', (_message.Message,), {
  'DESCRIPTOR' : _MODELMETADATA,
  '__module__' : 'gfp_model_pb2'
  # @@protoc_insertion_point(class_scope:GfpModel.ModelMetadata)
  })
_sym_db.RegisterMessage(ModelMetadata)

SvmfpModel = _reflection.GeneratedProtocolMessageType('SvmfpModel', (_message.Message,), {
  'DESCRIPTOR' : _SVMFPMODEL,
  '__module__' : 'gfp_model_pb2'
  # @@protoc_insertion_point(class_scope:GfpModel.SvmfpModel)
  })
_sym_db.RegisterMessage(SvmfpModel)

LightGbmModel = _reflection.GeneratedProtocolMessageType('LightGbmModel', (_message.Message,), {
  'DESCRIPTOR' : _LIGHTGBMMODEL,
  '__module__' : 'gfp_model_pb2'
  # @@protoc_insertion_point(class_scope:GfpModel.LightGbmModel)
  })
_sym_db.RegisterMessage(LightGbmModel)


# @@protoc_insertion_point(module_scope)
