# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: svmfp_model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='svmfp_model.proto',
  package='SvmfpModel',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11svmfp_model.proto\x12\nSvmfpModel\"\x9c\x04\n\nSvmfpModel\x12\x1a\n\rresponse_name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x19\n\x0c\x66ingerprints\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x17\n\nbit_subset\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x15\n\x08\x62it_xref\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x16\n\ttrain_gfp\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x1c\n\x0fsupport_vectors\x18\x06 \x01(\tH\x05\x88\x01\x01\x12\x18\n\x0bthreshold_b\x18\x07 \x01(\x01H\x06\x88\x01\x01\x12$\n\x17\x63lass_label_translation\x18\x08 \x01(\tH\x07\x88\x01\x01\x12\x1d\n\x10response_scaling\x18\t \x01(\tH\x08\x88\x01\x01\x12\x17\n\ndate_built\x18\n \x01(\tH\t\x88\x01\x01\x12(\n\x1b\x66latten_sparse_fingerprints\x18\x0b \x01(\x08H\n\x88\x01\x01\x42\x10\n\x0e_response_nameB\x0f\n\r_fingerprintsB\r\n\x0b_bit_subsetB\x0b\n\t_bit_xrefB\x0c\n\n_train_gfpB\x12\n\x10_support_vectorsB\x0e\n\x0c_threshold_bB\x1a\n\x18_class_label_translationB\x13\n\x11_response_scalingB\r\n\x0b_date_builtB\x1e\n\x1c_flatten_sparse_fingerprintsb\x06proto3'
)




_SVMFPMODEL = _descriptor.Descriptor(
  name='SvmfpModel',
  full_name='SvmfpModel.SvmfpModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response_name', full_name='SvmfpModel.SvmfpModel.response_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fingerprints', full_name='SvmfpModel.SvmfpModel.fingerprints', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bit_subset', full_name='SvmfpModel.SvmfpModel.bit_subset', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bit_xref', full_name='SvmfpModel.SvmfpModel.bit_xref', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='train_gfp', full_name='SvmfpModel.SvmfpModel.train_gfp', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='support_vectors', full_name='SvmfpModel.SvmfpModel.support_vectors', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='threshold_b', full_name='SvmfpModel.SvmfpModel.threshold_b', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='class_label_translation', full_name='SvmfpModel.SvmfpModel.class_label_translation', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response_scaling', full_name='SvmfpModel.SvmfpModel.response_scaling', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date_built', full_name='SvmfpModel.SvmfpModel.date_built', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flatten_sparse_fingerprints', full_name='SvmfpModel.SvmfpModel.flatten_sparse_fingerprints', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_response_name', full_name='SvmfpModel.SvmfpModel._response_name',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_fingerprints', full_name='SvmfpModel.SvmfpModel._fingerprints',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_bit_subset', full_name='SvmfpModel.SvmfpModel._bit_subset',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_bit_xref', full_name='SvmfpModel.SvmfpModel._bit_xref',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_train_gfp', full_name='SvmfpModel.SvmfpModel._train_gfp',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_support_vectors', full_name='SvmfpModel.SvmfpModel._support_vectors',
      index=5, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_threshold_b', full_name='SvmfpModel.SvmfpModel._threshold_b',
      index=6, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_class_label_translation', full_name='SvmfpModel.SvmfpModel._class_label_translation',
      index=7, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_response_scaling', full_name='SvmfpModel.SvmfpModel._response_scaling',
      index=8, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_date_built', full_name='SvmfpModel.SvmfpModel._date_built',
      index=9, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_flatten_sparse_fingerprints', full_name='SvmfpModel.SvmfpModel._flatten_sparse_fingerprints',
      index=10, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=34,
  serialized_end=574,
)

_SVMFPMODEL.oneofs_by_name['_response_name'].fields.append(
  _SVMFPMODEL.fields_by_name['response_name'])
_SVMFPMODEL.fields_by_name['response_name'].containing_oneof = _SVMFPMODEL.oneofs_by_name['_response_name']
_SVMFPMODEL.oneofs_by_name['_fingerprints'].fields.append(
  _SVMFPMODEL.fields_by_name['fingerprints'])
_SVMFPMODEL.fields_by_name['fingerprints'].containing_oneof = _SVMFPMODEL.oneofs_by_name['_fingerprints']
_SVMFPMODEL.oneofs_by_name['_bit_subset'].fields.append(
  _SVMFPMODEL.fields_by_name['bit_subset'])
_SVMFPMODEL.fields_by_name['bit_subset'].containing_oneof = _SVMFPMODEL.oneofs_by_name['_bit_subset']
_SVMFPMODEL.oneofs_by_name['_bit_xref'].fields.append(
  _SVMFPMODEL.fields_by_name['bit_xref'])
_SVMFPMODEL.fields_by_name['bit_xref'].containing_oneof = _SVMFPMODEL.oneofs_by_name['_bit_xref']
_SVMFPMODEL.oneofs_by_name['_train_gfp'].fields.append(
  _SVMFPMODEL.fields_by_name['train_gfp'])
_SVMFPMODEL.fields_by_name['train_gfp'].containing_oneof = _SVMFPMODEL.oneofs_by_name['_train_gfp']
_SVMFPMODEL.oneofs_by_name['_support_vectors'].fields.append(
  _SVMFPMODEL.fields_by_name['support_vectors'])
_SVMFPMODEL.fields_by_name['support_vectors'].containing_oneof = _SVMFPMODEL.oneofs_by_name['_support_vectors']
_SVMFPMODEL.oneofs_by_name['_threshold_b'].fields.append(
  _SVMFPMODEL.fields_by_name['threshold_b'])
_SVMFPMODEL.fields_by_name['threshold_b'].containing_oneof = _SVMFPMODEL.oneofs_by_name['_threshold_b']
_SVMFPMODEL.oneofs_by_name['_class_label_translation'].fields.append(
  _SVMFPMODEL.fields_by_name['class_label_translation'])
_SVMFPMODEL.fields_by_name['class_label_translation'].containing_oneof = _SVMFPMODEL.oneofs_by_name['_class_label_translation']
_SVMFPMODEL.oneofs_by_name['_response_scaling'].fields.append(
  _SVMFPMODEL.fields_by_name['response_scaling'])
_SVMFPMODEL.fields_by_name['response_scaling'].containing_oneof = _SVMFPMODEL.oneofs_by_name['_response_scaling']
_SVMFPMODEL.oneofs_by_name['_date_built'].fields.append(
  _SVMFPMODEL.fields_by_name['date_built'])
_SVMFPMODEL.fields_by_name['date_built'].containing_oneof = _SVMFPMODEL.oneofs_by_name['_date_built']
_SVMFPMODEL.oneofs_by_name['_flatten_sparse_fingerprints'].fields.append(
  _SVMFPMODEL.fields_by_name['flatten_sparse_fingerprints'])
_SVMFPMODEL.fields_by_name['flatten_sparse_fingerprints'].containing_oneof = _SVMFPMODEL.oneofs_by_name['_flatten_sparse_fingerprints']
DESCRIPTOR.message_types_by_name['SvmfpModel'] = _SVMFPMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SvmfpModel = _reflection.GeneratedProtocolMessageType('SvmfpModel', (_message.Message,), {
  'DESCRIPTOR' : _SVMFPMODEL,
  '__module__' : 'svmfp_model_pb2'
  # @@protoc_insertion_point(class_scope:SvmfpModel.SvmfpModel)
  })
_sym_db.RegisterMessage(SvmfpModel)


# @@protoc_insertion_point(module_scope)
