cc_library(
    name = "iwcmdline",
    visibility = ["//visibility:public"],
    srcs = ["cmdline.cc",
            "cmdline_stdstring.cc",
    ],
    hdrs = ["cmdline.h",
    ],
    deps = [
        "//Foundational/iwmisc:iwconfig",
        "//Foundational/iwstring:iwstring",
    ],
)
