// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Molecule_Lib/toggle_kekule_form.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Molecule_5fLib_2ftoggle_5fkekule_5fform_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Molecule_5fLib_2ftoggle_5fkekule_5fform_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3013000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Molecule_Lib/substructure.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Molecule_5fLib_2ftoggle_5fkekule_5fform_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Molecule_5fLib_2ftoggle_5fkekule_5fform_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Molecule_5fLib_2ftoggle_5fkekule_5fform_2eproto;
namespace ToggleKekuleForm {
class KekuleBond;
class KekuleBondDefaultTypeInternal;
extern KekuleBondDefaultTypeInternal _KekuleBond_default_instance_;
class ToggleKekuleForm;
class ToggleKekuleFormDefaultTypeInternal;
extern ToggleKekuleFormDefaultTypeInternal _ToggleKekuleForm_default_instance_;
}  // namespace ToggleKekuleForm
PROTOBUF_NAMESPACE_OPEN
template<> ::ToggleKekuleForm::KekuleBond* Arena::CreateMaybeMessage<::ToggleKekuleForm::KekuleBond>(Arena*);
template<> ::ToggleKekuleForm::ToggleKekuleForm* Arena::CreateMaybeMessage<::ToggleKekuleForm::ToggleKekuleForm>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ToggleKekuleForm {

// ===================================================================

class KekuleBond PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ToggleKekuleForm.KekuleBond) */ {
 public:
  inline KekuleBond() : KekuleBond(nullptr) {}
  virtual ~KekuleBond();

  KekuleBond(const KekuleBond& from);
  KekuleBond(KekuleBond&& from) noexcept
    : KekuleBond() {
    *this = ::std::move(from);
  }

  inline KekuleBond& operator=(const KekuleBond& from) {
    CopyFrom(from);
    return *this;
  }
  inline KekuleBond& operator=(KekuleBond&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const KekuleBond& default_instance();

  static inline const KekuleBond* internal_default_instance() {
    return reinterpret_cast<const KekuleBond*>(
               &_KekuleBond_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(KekuleBond& a, KekuleBond& b) {
    a.Swap(&b);
  }
  inline void Swap(KekuleBond* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(KekuleBond* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline KekuleBond* New() const final {
    return CreateMaybeMessage<KekuleBond>(nullptr);
  }

  KekuleBond* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<KekuleBond>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const KekuleBond& from);
  void MergeFrom(const KekuleBond& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(KekuleBond* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ToggleKekuleForm.KekuleBond";
  }
  protected:
  explicit KekuleBond(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Molecule_5fLib_2ftoggle_5fkekule_5fform_2eproto);
    return ::descriptor_table_Molecule_5fLib_2ftoggle_5fkekule_5fform_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kA1FieldNumber = 1,
    kA2FieldNumber = 2,
    kBtypeFieldNumber = 3,
  };
  // optional int32 a1 = 1;
  bool has_a1() const;
  private:
  bool _internal_has_a1() const;
  public:
  void clear_a1();
  ::PROTOBUF_NAMESPACE_ID::int32 a1() const;
  void set_a1(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_a1() const;
  void _internal_set_a1(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // optional int32 a2 = 2;
  bool has_a2() const;
  private:
  bool _internal_has_a2() const;
  public:
  void clear_a2();
  ::PROTOBUF_NAMESPACE_ID::int32 a2() const;
  void set_a2(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_a2() const;
  void _internal_set_a2(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // optional .SubstructureSearch.BondType btype = 3;
  bool has_btype() const;
  private:
  bool _internal_has_btype() const;
  public:
  void clear_btype();
  ::SubstructureSearch::BondType btype() const;
  void set_btype(::SubstructureSearch::BondType value);
  private:
  ::SubstructureSearch::BondType _internal_btype() const;
  void _internal_set_btype(::SubstructureSearch::BondType value);
  public:

  // @@protoc_insertion_point(class_scope:ToggleKekuleForm.KekuleBond)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::int32 a1_;
  ::PROTOBUF_NAMESPACE_ID::int32 a2_;
  int btype_;
  friend struct ::TableStruct_Molecule_5fLib_2ftoggle_5fkekule_5fform_2eproto;
};
// -------------------------------------------------------------------

class ToggleKekuleForm PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ToggleKekuleForm.ToggleKekuleForm) */ {
 public:
  inline ToggleKekuleForm() : ToggleKekuleForm(nullptr) {}
  virtual ~ToggleKekuleForm();

  ToggleKekuleForm(const ToggleKekuleForm& from);
  ToggleKekuleForm(ToggleKekuleForm&& from) noexcept
    : ToggleKekuleForm() {
    *this = ::std::move(from);
  }

  inline ToggleKekuleForm& operator=(const ToggleKekuleForm& from) {
    CopyFrom(from);
    return *this;
  }
  inline ToggleKekuleForm& operator=(ToggleKekuleForm&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ToggleKekuleForm& default_instance();

  static inline const ToggleKekuleForm* internal_default_instance() {
    return reinterpret_cast<const ToggleKekuleForm*>(
               &_ToggleKekuleForm_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ToggleKekuleForm& a, ToggleKekuleForm& b) {
    a.Swap(&b);
  }
  inline void Swap(ToggleKekuleForm* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ToggleKekuleForm* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ToggleKekuleForm* New() const final {
    return CreateMaybeMessage<ToggleKekuleForm>(nullptr);
  }

  ToggleKekuleForm* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ToggleKekuleForm>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ToggleKekuleForm& from);
  void MergeFrom(const ToggleKekuleForm& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ToggleKekuleForm* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ToggleKekuleForm.ToggleKekuleForm";
  }
  protected:
  explicit ToggleKekuleForm(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Molecule_5fLib_2ftoggle_5fkekule_5fform_2eproto);
    return ::descriptor_table_Molecule_5fLib_2ftoggle_5fkekule_5fform_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBondFieldNumber = 1,
  };
  // repeated .ToggleKekuleForm.KekuleBond bond = 1;
  int bond_size() const;
  private:
  int _internal_bond_size() const;
  public:
  void clear_bond();
  ::ToggleKekuleForm::KekuleBond* mutable_bond(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ToggleKekuleForm::KekuleBond >*
      mutable_bond();
  private:
  const ::ToggleKekuleForm::KekuleBond& _internal_bond(int index) const;
  ::ToggleKekuleForm::KekuleBond* _internal_add_bond();
  public:
  const ::ToggleKekuleForm::KekuleBond& bond(int index) const;
  ::ToggleKekuleForm::KekuleBond* add_bond();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ToggleKekuleForm::KekuleBond >&
      bond() const;

  // @@protoc_insertion_point(class_scope:ToggleKekuleForm.ToggleKekuleForm)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ToggleKekuleForm::KekuleBond > bond_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Molecule_5fLib_2ftoggle_5fkekule_5fform_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// KekuleBond

// optional int32 a1 = 1;
inline bool KekuleBond::_internal_has_a1() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool KekuleBond::has_a1() const {
  return _internal_has_a1();
}
inline void KekuleBond::clear_a1() {
  a1_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 KekuleBond::_internal_a1() const {
  return a1_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 KekuleBond::a1() const {
  // @@protoc_insertion_point(field_get:ToggleKekuleForm.KekuleBond.a1)
  return _internal_a1();
}
inline void KekuleBond::_internal_set_a1(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000001u;
  a1_ = value;
}
inline void KekuleBond::set_a1(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_a1(value);
  // @@protoc_insertion_point(field_set:ToggleKekuleForm.KekuleBond.a1)
}

// optional int32 a2 = 2;
inline bool KekuleBond::_internal_has_a2() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool KekuleBond::has_a2() const {
  return _internal_has_a2();
}
inline void KekuleBond::clear_a2() {
  a2_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 KekuleBond::_internal_a2() const {
  return a2_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 KekuleBond::a2() const {
  // @@protoc_insertion_point(field_get:ToggleKekuleForm.KekuleBond.a2)
  return _internal_a2();
}
inline void KekuleBond::_internal_set_a2(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  a2_ = value;
}
inline void KekuleBond::set_a2(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_a2(value);
  // @@protoc_insertion_point(field_set:ToggleKekuleForm.KekuleBond.a2)
}

// optional .SubstructureSearch.BondType btype = 3;
inline bool KekuleBond::_internal_has_btype() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool KekuleBond::has_btype() const {
  return _internal_has_btype();
}
inline void KekuleBond::clear_btype() {
  btype_ = 3;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::SubstructureSearch::BondType KekuleBond::_internal_btype() const {
  return static_cast< ::SubstructureSearch::BondType >(btype_);
}
inline ::SubstructureSearch::BondType KekuleBond::btype() const {
  // @@protoc_insertion_point(field_get:ToggleKekuleForm.KekuleBond.btype)
  return _internal_btype();
}
inline void KekuleBond::_internal_set_btype(::SubstructureSearch::BondType value) {
  assert(::SubstructureSearch::BondType_IsValid(value));
  _has_bits_[0] |= 0x00000004u;
  btype_ = value;
}
inline void KekuleBond::set_btype(::SubstructureSearch::BondType value) {
  _internal_set_btype(value);
  // @@protoc_insertion_point(field_set:ToggleKekuleForm.KekuleBond.btype)
}

// -------------------------------------------------------------------

// ToggleKekuleForm

// repeated .ToggleKekuleForm.KekuleBond bond = 1;
inline int ToggleKekuleForm::_internal_bond_size() const {
  return bond_.size();
}
inline int ToggleKekuleForm::bond_size() const {
  return _internal_bond_size();
}
inline void ToggleKekuleForm::clear_bond() {
  bond_.Clear();
}
inline ::ToggleKekuleForm::KekuleBond* ToggleKekuleForm::mutable_bond(int index) {
  // @@protoc_insertion_point(field_mutable:ToggleKekuleForm.ToggleKekuleForm.bond)
  return bond_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ToggleKekuleForm::KekuleBond >*
ToggleKekuleForm::mutable_bond() {
  // @@protoc_insertion_point(field_mutable_list:ToggleKekuleForm.ToggleKekuleForm.bond)
  return &bond_;
}
inline const ::ToggleKekuleForm::KekuleBond& ToggleKekuleForm::_internal_bond(int index) const {
  return bond_.Get(index);
}
inline const ::ToggleKekuleForm::KekuleBond& ToggleKekuleForm::bond(int index) const {
  // @@protoc_insertion_point(field_get:ToggleKekuleForm.ToggleKekuleForm.bond)
  return _internal_bond(index);
}
inline ::ToggleKekuleForm::KekuleBond* ToggleKekuleForm::_internal_add_bond() {
  return bond_.Add();
}
inline ::ToggleKekuleForm::KekuleBond* ToggleKekuleForm::add_bond() {
  // @@protoc_insertion_point(field_add:ToggleKekuleForm.ToggleKekuleForm.bond)
  return _internal_add_bond();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ToggleKekuleForm::KekuleBond >&
ToggleKekuleForm::bond() const {
  // @@protoc_insertion_point(field_list:ToggleKekuleForm.ToggleKekuleForm.bond)
  return bond_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ToggleKekuleForm

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Molecule_5fLib_2ftoggle_5fkekule_5fform_2eproto
