# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Utilities/General/catboost_options.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(Utilities/General/catboost_options.proto\"\xd5\x02\n\x0f\x43\x61tboostOptions\x12\x39\n\rstring_option\x18\x01 \x03(\x0b\x32\".CatboostOptions.StringOptionEntry\x12\x33\n\nint_option\x18\x02 \x03(\x0b\x32\x1f.CatboostOptions.IntOptionEntry\x12\x37\n\x0c\x66loat_option\x18\x03 \x03(\x0b\x32!.CatboostOptions.FloatOptionEntry\x1a\x33\n\x11StringOptionEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x30\n\x0eIntOptionEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a\x32\n\x10\x46loatOptionEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x62\x06proto3')



_CATBOOSTOPTIONS = DESCRIPTOR.message_types_by_name['CatboostOptions']
_CATBOOSTOPTIONS_STRINGOPTIONENTRY = _CATBOOSTOPTIONS.nested_types_by_name['StringOptionEntry']
_CATBOOSTOPTIONS_INTOPTIONENTRY = _CATBOOSTOPTIONS.nested_types_by_name['IntOptionEntry']
_CATBOOSTOPTIONS_FLOATOPTIONENTRY = _CATBOOSTOPTIONS.nested_types_by_name['FloatOptionEntry']
CatboostOptions = _reflection.GeneratedProtocolMessageType('CatboostOptions', (_message.Message,), {

  'StringOptionEntry' : _reflection.GeneratedProtocolMessageType('StringOptionEntry', (_message.Message,), {
    'DESCRIPTOR' : _CATBOOSTOPTIONS_STRINGOPTIONENTRY,
    '__module__' : 'Utilities.General.catboost_options_pb2'
    # @@protoc_insertion_point(class_scope:CatboostOptions.StringOptionEntry)
    })
  ,

  'IntOptionEntry' : _reflection.GeneratedProtocolMessageType('IntOptionEntry', (_message.Message,), {
    'DESCRIPTOR' : _CATBOOSTOPTIONS_INTOPTIONENTRY,
    '__module__' : 'Utilities.General.catboost_options_pb2'
    # @@protoc_insertion_point(class_scope:CatboostOptions.IntOptionEntry)
    })
  ,

  'FloatOptionEntry' : _reflection.GeneratedProtocolMessageType('FloatOptionEntry', (_message.Message,), {
    'DESCRIPTOR' : _CATBOOSTOPTIONS_FLOATOPTIONENTRY,
    '__module__' : 'Utilities.General.catboost_options_pb2'
    # @@protoc_insertion_point(class_scope:CatboostOptions.FloatOptionEntry)
    })
  ,
  'DESCRIPTOR' : _CATBOOSTOPTIONS,
  '__module__' : 'Utilities.General.catboost_options_pb2'
  # @@protoc_insertion_point(class_scope:CatboostOptions)
  })
_sym_db.RegisterMessage(CatboostOptions)
_sym_db.RegisterMessage(CatboostOptions.StringOptionEntry)
_sym_db.RegisterMessage(CatboostOptions.IntOptionEntry)
_sym_db.RegisterMessage(CatboostOptions.FloatOptionEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CATBOOSTOPTIONS_STRINGOPTIONENTRY._options = None
  _CATBOOSTOPTIONS_STRINGOPTIONENTRY._serialized_options = b'8\001'
  _CATBOOSTOPTIONS_INTOPTIONENTRY._options = None
  _CATBOOSTOPTIONS_INTOPTIONENTRY._serialized_options = b'8\001'
  _CATBOOSTOPTIONS_FLOATOPTIONENTRY._options = None
  _CATBOOSTOPTIONS_FLOATOPTIONENTRY._serialized_options = b'8\001'
  _CATBOOSTOPTIONS._serialized_start=45
  _CATBOOSTOPTIONS._serialized_end=386
  _CATBOOSTOPTIONS_STRINGOPTIONENTRY._serialized_start=233
  _CATBOOSTOPTIONS_STRINGOPTIONENTRY._serialized_end=284
  _CATBOOSTOPTIONS_INTOPTIONENTRY._serialized_start=286
  _CATBOOSTOPTIONS_INTOPTIONENTRY._serialized_end=334
  _CATBOOSTOPTIONS_FLOATOPTIONENTRY._serialized_start=336
  _CATBOOSTOPTIONS_FLOATOPTIONENTRY._serialized_end=386
# @@protoc_insertion_point(module_scope)
