# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catboost_options.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='catboost_options.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x63\x61tboost_options.proto\"\xd5\x02\n\x0f\x43\x61tboostOptions\x12\x39\n\rstring_option\x18\x01 \x03(\x0b\x32\".CatboostOptions.StringOptionEntry\x12\x33\n\nint_option\x18\x02 \x03(\x0b\x32\x1f.CatboostOptions.IntOptionEntry\x12\x37\n\x0c\x66loat_option\x18\x03 \x03(\x0b\x32!.CatboostOptions.FloatOptionEntry\x1a\x33\n\x11StringOptionEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x30\n\x0eIntOptionEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a\x32\n\x10\x46loatOptionEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x62\x06proto3'
)




_CATBOOSTOPTIONS_STRINGOPTIONENTRY = _descriptor.Descriptor(
  name='StringOptionEntry',
  full_name='CatboostOptions.StringOptionEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='CatboostOptions.StringOptionEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='CatboostOptions.StringOptionEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=266,
)

_CATBOOSTOPTIONS_INTOPTIONENTRY = _descriptor.Descriptor(
  name='IntOptionEntry',
  full_name='CatboostOptions.IntOptionEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='CatboostOptions.IntOptionEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='CatboostOptions.IntOptionEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=316,
)

_CATBOOSTOPTIONS_FLOATOPTIONENTRY = _descriptor.Descriptor(
  name='FloatOptionEntry',
  full_name='CatboostOptions.FloatOptionEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='CatboostOptions.FloatOptionEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='CatboostOptions.FloatOptionEntry.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=318,
  serialized_end=368,
)

_CATBOOSTOPTIONS = _descriptor.Descriptor(
  name='CatboostOptions',
  full_name='CatboostOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='string_option', full_name='CatboostOptions.string_option', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='int_option', full_name='CatboostOptions.int_option', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='float_option', full_name='CatboostOptions.float_option', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CATBOOSTOPTIONS_STRINGOPTIONENTRY, _CATBOOSTOPTIONS_INTOPTIONENTRY, _CATBOOSTOPTIONS_FLOATOPTIONENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=368,
)

_CATBOOSTOPTIONS_STRINGOPTIONENTRY.containing_type = _CATBOOSTOPTIONS
_CATBOOSTOPTIONS_INTOPTIONENTRY.containing_type = _CATBOOSTOPTIONS
_CATBOOSTOPTIONS_FLOATOPTIONENTRY.containing_type = _CATBOOSTOPTIONS
_CATBOOSTOPTIONS.fields_by_name['string_option'].message_type = _CATBOOSTOPTIONS_STRINGOPTIONENTRY
_CATBOOSTOPTIONS.fields_by_name['int_option'].message_type = _CATBOOSTOPTIONS_INTOPTIONENTRY
_CATBOOSTOPTIONS.fields_by_name['float_option'].message_type = _CATBOOSTOPTIONS_FLOATOPTIONENTRY
DESCRIPTOR.message_types_by_name['CatboostOptions'] = _CATBOOSTOPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CatboostOptions = _reflection.GeneratedProtocolMessageType('CatboostOptions', (_message.Message,), {

  'StringOptionEntry' : _reflection.GeneratedProtocolMessageType('StringOptionEntry', (_message.Message,), {
    'DESCRIPTOR' : _CATBOOSTOPTIONS_STRINGOPTIONENTRY,
    '__module__' : 'catboost_options_pb2'
    # @@protoc_insertion_point(class_scope:CatboostOptions.StringOptionEntry)
    })
  ,

  'IntOptionEntry' : _reflection.GeneratedProtocolMessageType('IntOptionEntry', (_message.Message,), {
    'DESCRIPTOR' : _CATBOOSTOPTIONS_INTOPTIONENTRY,
    '__module__' : 'catboost_options_pb2'
    # @@protoc_insertion_point(class_scope:CatboostOptions.IntOptionEntry)
    })
  ,

  'FloatOptionEntry' : _reflection.GeneratedProtocolMessageType('FloatOptionEntry', (_message.Message,), {
    'DESCRIPTOR' : _CATBOOSTOPTIONS_FLOATOPTIONENTRY,
    '__module__' : 'catboost_options_pb2'
    # @@protoc_insertion_point(class_scope:CatboostOptions.FloatOptionEntry)
    })
  ,
  'DESCRIPTOR' : _CATBOOSTOPTIONS,
  '__module__' : 'catboost_options_pb2'
  # @@protoc_insertion_point(class_scope:CatboostOptions)
  })
_sym_db.RegisterMessage(CatboostOptions)
_sym_db.RegisterMessage(CatboostOptions.StringOptionEntry)
_sym_db.RegisterMessage(CatboostOptions.IntOptionEntry)
_sym_db.RegisterMessage(CatboostOptions.FloatOptionEntry)


_CATBOOSTOPTIONS_STRINGOPTIONENTRY._options = None
_CATBOOSTOPTIONS_INTOPTIONENTRY._options = None
_CATBOOSTOPTIONS_FLOATOPTIONENTRY._options = None
# @@protoc_insertion_point(module_scope)
