# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: feature_scaling.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='feature_scaling.proto',
  package='FeatureScaling',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x66\x65\x61ture_scaling.proto\x12\x0e\x46\x65\x61tureScaling\"\x84\x01\n\x0e\x46\x65\x61tureScaling\x12\x10\n\x03min\x18\x01 \x01(\x01H\x00\x88\x01\x01\x12\x10\n\x03max\x18\x02 \x01(\x01H\x01\x88\x01\x01\x12\x15\n\x08nsamples\x18\x03 \x01(\rH\x02\x88\x01\x01\x12\x11\n\x04mean\x18\x04 \x01(\x01H\x03\x88\x01\x01\x42\x06\n\x04_minB\x06\n\x04_maxB\x0b\n\t_nsamplesB\x07\n\x05_meanb\x06proto3'
)




_FEATURESCALING = _descriptor.Descriptor(
  name='FeatureScaling',
  full_name='FeatureScaling.FeatureScaling',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='min', full_name='FeatureScaling.FeatureScaling.min', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max', full_name='FeatureScaling.FeatureScaling.max', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nsamples', full_name='FeatureScaling.FeatureScaling.nsamples', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean', full_name='FeatureScaling.FeatureScaling.mean', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_min', full_name='FeatureScaling.FeatureScaling._min',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_max', full_name='FeatureScaling.FeatureScaling._max',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_nsamples', full_name='FeatureScaling.FeatureScaling._nsamples',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_mean', full_name='FeatureScaling.FeatureScaling._mean',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=42,
  serialized_end=174,
)

_FEATURESCALING.oneofs_by_name['_min'].fields.append(
  _FEATURESCALING.fields_by_name['min'])
_FEATURESCALING.fields_by_name['min'].containing_oneof = _FEATURESCALING.oneofs_by_name['_min']
_FEATURESCALING.oneofs_by_name['_max'].fields.append(
  _FEATURESCALING.fields_by_name['max'])
_FEATURESCALING.fields_by_name['max'].containing_oneof = _FEATURESCALING.oneofs_by_name['_max']
_FEATURESCALING.oneofs_by_name['_nsamples'].fields.append(
  _FEATURESCALING.fields_by_name['nsamples'])
_FEATURESCALING.fields_by_name['nsamples'].containing_oneof = _FEATURESCALING.oneofs_by_name['_nsamples']
_FEATURESCALING.oneofs_by_name['_mean'].fields.append(
  _FEATURESCALING.fields_by_name['mean'])
_FEATURESCALING.fields_by_name['mean'].containing_oneof = _FEATURESCALING.oneofs_by_name['_mean']
DESCRIPTOR.message_types_by_name['FeatureScaling'] = _FEATURESCALING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FeatureScaling = _reflection.GeneratedProtocolMessageType('FeatureScaling', (_message.Message,), {
  'DESCRIPTOR' : _FEATURESCALING,
  '__module__' : 'feature_scaling_pb2'
  # @@protoc_insertion_point(class_scope:FeatureScaling.FeatureScaling)
  })
_sym_db.RegisterMessage(FeatureScaling)


# @@protoc_insertion_point(module_scope)
