# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Utilities/General/feature_scaling.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'Utilities/General/feature_scaling.proto\x12\x0e\x46\x65\x61tureScaling\"J\n\x0e\x46\x65\x61tureScaling\x12\x0b\n\x03min\x18\x01 \x01(\x01\x12\x0b\n\x03max\x18\x02 \x01(\x01\x12\x10\n\x08nsamples\x18\x03 \x01(\r\x12\x0c\n\x04mean\x18\x04 \x01(\x01\x62\x06proto3')



_FEATURESCALING = DESCRIPTOR.message_types_by_name['FeatureScaling']
FeatureScaling = _reflection.GeneratedProtocolMessageType('FeatureScaling', (_message.Message,), {
  'DESCRIPTOR' : _FEATURESCALING,
  '__module__' : 'Utilities.General.feature_scaling_pb2'
  # @@protoc_insertion_point(class_scope:FeatureScaling.FeatureScaling)
  })
_sym_db.RegisterMessage(FeatureScaling)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FEATURESCALING._serialized_start=59
  _FEATURESCALING._serialized_end=133
# @@protoc_insertion_point(module_scope)
