cc_binary(
    name = "leveldb_list",
    srcs = [
        "leveldb_list.cc",
    ],
    deps = [
        "//Foundational/cmdline:iwcmdline",
    ],
    linkopts = [
        "-lz",
        "-lre2",
        "-lleveldb",
    ],
)
