cc_library(
    name = "iwhistogram",
    visibility = [
        "//visibility:public",
    ],
    srcs = [
        "iwhistogram.cc",
    ],
    hdrs = [
        "iwhistogram.h",
    ],
    deps = [
        "//Foundational/iwstring:iwstring",
    ],
)

