# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gfp_to_svm_lite.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gfp_to_svm_lite.proto',
  package='GfpBitSubset',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15gfp_to_svm_lite.proto\x12\x0cGfpBitSubset\"?\n\tBitSubset\x12\x14\n\x07\x66p_name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x10\n\x04\x62its\x18\x02 \x03(\rB\x02\x10\x01\x42\n\n\x08_fp_name\"\xa1\x01\n\x07\x42itXref\x12\x14\n\x07\x66p_name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12?\n\x0e\x62it_to_feature\x18\x02 \x03(\x0b\x32\'.GfpBitSubset.BitXref.BitToFeatureEntry\x1a\x33\n\x11\x42itToFeatureEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x42\n\n\x08_fp_name\"\xb4\x01\n\x06Params\x12\x14\n\x07support\x18\x01 \x01(\rH\x00\x88\x01\x01\x12(\n\x1b\x66latten_sparse_fingerprints\x18\x02 \x01(\x08H\x01\x88\x01\x01\x12#\n\x16highest_feature_number\x18\x03 \x01(\rH\x02\x88\x01\x01\x42\n\n\x08_supportB\x1e\n\x1c_flatten_sparse_fingerprintsB\x19\n\x17_highest_feature_number\"\xae\x01\n\x0cGfpBitSubset\x12\x32\n\x04xref\x18\x01 \x03(\x0b\x32$.GfpBitSubset.GfpBitSubset.XrefEntry\x12$\n\x06params\x18\x02 \x01(\x0b\x32\x14.GfpBitSubset.Params\x1a\x44\n\tXrefEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.GfpBitSubset.BitSubset:\x02\x38\x01\"\xb2\x01\n\x0fGfpBitToFeature\x12\x35\n\x04xref\x18\x01 \x03(\x0b\x32\'.GfpBitSubset.GfpBitToFeature.XrefEntry\x12$\n\x06params\x18\x02 \x01(\x0b\x32\x14.GfpBitSubset.Params\x1a\x42\n\tXrefEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.GfpBitSubset.BitXref:\x02\x38\x01\x62\x06proto3'
)




_BITSUBSET = _descriptor.Descriptor(
  name='BitSubset',
  full_name='GfpBitSubset.BitSubset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fp_name', full_name='GfpBitSubset.BitSubset.fp_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bits', full_name='GfpBitSubset.BitSubset.bits', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_fp_name', full_name='GfpBitSubset.BitSubset._fp_name',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=39,
  serialized_end=102,
)


_BITXREF_BITTOFEATUREENTRY = _descriptor.Descriptor(
  name='BitToFeatureEntry',
  full_name='GfpBitSubset.BitXref.BitToFeatureEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='GfpBitSubset.BitXref.BitToFeatureEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='GfpBitSubset.BitXref.BitToFeatureEntry.value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=254,
)

_BITXREF = _descriptor.Descriptor(
  name='BitXref',
  full_name='GfpBitSubset.BitXref',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fp_name', full_name='GfpBitSubset.BitXref.fp_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bit_to_feature', full_name='GfpBitSubset.BitXref.bit_to_feature', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_BITXREF_BITTOFEATUREENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_fp_name', full_name='GfpBitSubset.BitXref._fp_name',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=105,
  serialized_end=266,
)


_PARAMS = _descriptor.Descriptor(
  name='Params',
  full_name='GfpBitSubset.Params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='support', full_name='GfpBitSubset.Params.support', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flatten_sparse_fingerprints', full_name='GfpBitSubset.Params.flatten_sparse_fingerprints', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='highest_feature_number', full_name='GfpBitSubset.Params.highest_feature_number', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_support', full_name='GfpBitSubset.Params._support',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_flatten_sparse_fingerprints', full_name='GfpBitSubset.Params._flatten_sparse_fingerprints',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_highest_feature_number', full_name='GfpBitSubset.Params._highest_feature_number',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=269,
  serialized_end=449,
)


_GFPBITSUBSET_XREFENTRY = _descriptor.Descriptor(
  name='XrefEntry',
  full_name='GfpBitSubset.GfpBitSubset.XrefEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='GfpBitSubset.GfpBitSubset.XrefEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='GfpBitSubset.GfpBitSubset.XrefEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=558,
  serialized_end=626,
)

_GFPBITSUBSET = _descriptor.Descriptor(
  name='GfpBitSubset',
  full_name='GfpBitSubset.GfpBitSubset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='xref', full_name='GfpBitSubset.GfpBitSubset.xref', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='GfpBitSubset.GfpBitSubset.params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GFPBITSUBSET_XREFENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=452,
  serialized_end=626,
)


_GFPBITTOFEATURE_XREFENTRY = _descriptor.Descriptor(
  name='XrefEntry',
  full_name='GfpBitSubset.GfpBitToFeature.XrefEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='GfpBitSubset.GfpBitToFeature.XrefEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='GfpBitSubset.GfpBitToFeature.XrefEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=741,
  serialized_end=807,
)

_GFPBITTOFEATURE = _descriptor.Descriptor(
  name='GfpBitToFeature',
  full_name='GfpBitSubset.GfpBitToFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='xref', full_name='GfpBitSubset.GfpBitToFeature.xref', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='GfpBitSubset.GfpBitToFeature.params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GFPBITTOFEATURE_XREFENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=629,
  serialized_end=807,
)

_BITSUBSET.oneofs_by_name['_fp_name'].fields.append(
  _BITSUBSET.fields_by_name['fp_name'])
_BITSUBSET.fields_by_name['fp_name'].containing_oneof = _BITSUBSET.oneofs_by_name['_fp_name']
_BITXREF_BITTOFEATUREENTRY.containing_type = _BITXREF
_BITXREF.fields_by_name['bit_to_feature'].message_type = _BITXREF_BITTOFEATUREENTRY
_BITXREF.oneofs_by_name['_fp_name'].fields.append(
  _BITXREF.fields_by_name['fp_name'])
_BITXREF.fields_by_name['fp_name'].containing_oneof = _BITXREF.oneofs_by_name['_fp_name']
_PARAMS.oneofs_by_name['_support'].fields.append(
  _PARAMS.fields_by_name['support'])
_PARAMS.fields_by_name['support'].containing_oneof = _PARAMS.oneofs_by_name['_support']
_PARAMS.oneofs_by_name['_flatten_sparse_fingerprints'].fields.append(
  _PARAMS.fields_by_name['flatten_sparse_fingerprints'])
_PARAMS.fields_by_name['flatten_sparse_fingerprints'].containing_oneof = _PARAMS.oneofs_by_name['_flatten_sparse_fingerprints']
_PARAMS.oneofs_by_name['_highest_feature_number'].fields.append(
  _PARAMS.fields_by_name['highest_feature_number'])
_PARAMS.fields_by_name['highest_feature_number'].containing_oneof = _PARAMS.oneofs_by_name['_highest_feature_number']
_GFPBITSUBSET_XREFENTRY.fields_by_name['value'].message_type = _BITSUBSET
_GFPBITSUBSET_XREFENTRY.containing_type = _GFPBITSUBSET
_GFPBITSUBSET.fields_by_name['xref'].message_type = _GFPBITSUBSET_XREFENTRY
_GFPBITSUBSET.fields_by_name['params'].message_type = _PARAMS
_GFPBITTOFEATURE_XREFENTRY.fields_by_name['value'].message_type = _BITXREF
_GFPBITTOFEATURE_XREFENTRY.containing_type = _GFPBITTOFEATURE
_GFPBITTOFEATURE.fields_by_name['xref'].message_type = _GFPBITTOFEATURE_XREFENTRY
_GFPBITTOFEATURE.fields_by_name['params'].message_type = _PARAMS
DESCRIPTOR.message_types_by_name['BitSubset'] = _BITSUBSET
DESCRIPTOR.message_types_by_name['BitXref'] = _BITXREF
DESCRIPTOR.message_types_by_name['Params'] = _PARAMS
DESCRIPTOR.message_types_by_name['GfpBitSubset'] = _GFPBITSUBSET
DESCRIPTOR.message_types_by_name['GfpBitToFeature'] = _GFPBITTOFEATURE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BitSubset = _reflection.GeneratedProtocolMessageType('BitSubset', (_message.Message,), {
  'DESCRIPTOR' : _BITSUBSET,
  '__module__' : 'gfp_to_svm_lite_pb2'
  # @@protoc_insertion_point(class_scope:GfpBitSubset.BitSubset)
  })
_sym_db.RegisterMessage(BitSubset)

BitXref = _reflection.GeneratedProtocolMessageType('BitXref', (_message.Message,), {

  'BitToFeatureEntry' : _reflection.GeneratedProtocolMessageType('BitToFeatureEntry', (_message.Message,), {
    'DESCRIPTOR' : _BITXREF_BITTOFEATUREENTRY,
    '__module__' : 'gfp_to_svm_lite_pb2'
    # @@protoc_insertion_point(class_scope:GfpBitSubset.BitXref.BitToFeatureEntry)
    })
  ,
  'DESCRIPTOR' : _BITXREF,
  '__module__' : 'gfp_to_svm_lite_pb2'
  # @@protoc_insertion_point(class_scope:GfpBitSubset.BitXref)
  })
_sym_db.RegisterMessage(BitXref)
_sym_db.RegisterMessage(BitXref.BitToFeatureEntry)

Params = _reflection.GeneratedProtocolMessageType('Params', (_message.Message,), {
  'DESCRIPTOR' : _PARAMS,
  '__module__' : 'gfp_to_svm_lite_pb2'
  # @@protoc_insertion_point(class_scope:GfpBitSubset.Params)
  })
_sym_db.RegisterMessage(Params)

GfpBitSubset = _reflection.GeneratedProtocolMessageType('GfpBitSubset', (_message.Message,), {

  'XrefEntry' : _reflection.GeneratedProtocolMessageType('XrefEntry', (_message.Message,), {
    'DESCRIPTOR' : _GFPBITSUBSET_XREFENTRY,
    '__module__' : 'gfp_to_svm_lite_pb2'
    # @@protoc_insertion_point(class_scope:GfpBitSubset.GfpBitSubset.XrefEntry)
    })
  ,
  'DESCRIPTOR' : _GFPBITSUBSET,
  '__module__' : 'gfp_to_svm_lite_pb2'
  # @@protoc_insertion_point(class_scope:GfpBitSubset.GfpBitSubset)
  })
_sym_db.RegisterMessage(GfpBitSubset)
_sym_db.RegisterMessage(GfpBitSubset.XrefEntry)

GfpBitToFeature = _reflection.GeneratedProtocolMessageType('GfpBitToFeature', (_message.Message,), {

  'XrefEntry' : _reflection.GeneratedProtocolMessageType('XrefEntry', (_message.Message,), {
    'DESCRIPTOR' : _GFPBITTOFEATURE_XREFENTRY,
    '__module__' : 'gfp_to_svm_lite_pb2'
    # @@protoc_insertion_point(class_scope:GfpBitSubset.GfpBitToFeature.XrefEntry)
    })
  ,
  'DESCRIPTOR' : _GFPBITTOFEATURE,
  '__module__' : 'gfp_to_svm_lite_pb2'
  # @@protoc_insertion_point(class_scope:GfpBitSubset.GfpBitToFeature)
  })
_sym_db.RegisterMessage(GfpBitToFeature)
_sym_db.RegisterMessage(GfpBitToFeature.XrefEntry)


_BITSUBSET.fields_by_name['bits']._options = None
_BITXREF_BITTOFEATUREENTRY._options = None
_GFPBITSUBSET_XREFENTRY._options = None
_GFPBITTOFEATURE_XREFENTRY._options = None
# @@protoc_insertion_point(module_scope)
