// Use a database generated by generate_atom_separations to form
// new molecules based on matched atoms in an input stream

#include <fcntl.h>

#include <iostream>

#include "lmdb.h"

#include "google/protobuf/text_format.h"

#include "Foundational/cmdline/cmdline.h"

#include "Molecule_Lib/aromatic.h"
#include "Molecule_Lib/istream_and_type.h"
#include "Molecule_Lib/molecule.h"
#include "Molecule_Lib/qry_wstats.h"
#include "Molecule_Lib/rwsubstructure.h"
#include "Molecule_Lib/substructure.h"
#include "Molecule_Lib/standardise.h"
#include "Molecule_Lib/target.h"

#include "Molecule_Tools/atom_separations.h"

namespace separated_atoms {

using std::cerr;

void
Usage(int rc) {

  cerr << " -d <dbname>       database containing labelled cores (from generate_atom_separations)\n";
  cerr << " -q <qry>          queries that identify the break points\n";
  cerr << " -s <smarts>       queries\n"; 
  cerr << " -w <number>       number of bonds to break\n";
  cerr << " -c                remove chirality\n";
  cerr << " -l                strip to largest fragment\n";
  cerr << " -g ...            chemical standardisation\n";
  cerr << " -A ...            standard aromaticity options\n";
  cerr << " -E ...            standard element options\n";
  cerr << " -v                verbose output\n";

  ::exit(rc);
}

class CoreReplacement {
  private:
    int _verbose;

    int _molecules_read;

    int _reduce_to_largest_fragment;

    int _remove_chirality;

    IWString _database_name;
    MDB_env* mdb_env;
    MDB_txn* mdb_txn;
    MDB_dbi mdb_dbi;

    FileType _input_type;

    Chemical_Standardisation _chemical_standardisation;

    // One or more queries for identifying the core.
    // In order to be processed, the first query to match
    // must report 2 or more matches.
    // The number of matches is the connectivity of the
    // fragment to be replaced.
    resizable_array_p<Substructure_Hit_Statistics> _queries;

    int _no_query_match;
    int _cannot_identify_core;

    int _bonds_to_break;
    int _ignore_molecules_not_matching_queries;
    int _write_molecules_not_matching_queries;

  // Private functions

    int OpenDatabase();
    int HandleNoQueryMatch(Molecule& m, IWString_and_File_Descriptor& output);
    int Process(Molecule& m,
        const Set_of_Atoms& matched_atoms,
        IWString_and_File_Descriptor& output);

  public:
    CoreReplacement();

    int Initialise(Command_Line& cl);

    int Preprocess(Molecule& m);

    int Process(Molecule& m, IWString_and_File_Descriptor& output);

    int Report(std::ostream& output) const;

    FileType input_type() const {
      return _input_type;
    }
};

CoreReplacement::CoreReplacement() {
  _verbose = 0;
  _molecules_read = 0;
  _reduce_to_largest_fragment = 0;
  _remove_chirality = 0;
  _input_type = FILE_TYPE_INVALID;
  _bonds_to_break = 0;
  _no_query_match = 0;
  _cannot_identify_core = 0;
  _ignore_molecules_not_matching_queries = 0;
  _write_molecules_not_matching_queries = 0;

  mdb_env = nullptr;
  mdb_txn = nullptr;
  mdb_dbi = 0;
}

int
CoreReplacement::OpenDatabase() {
  int status =  mdb_env_create(&mdb_env);
  if (status != 0) {
    cerr << "Job::OpenDatabase:cannot create environment, status " << status << '\n';
    return 0;
  }


  unsigned int flags = 0;
  mdb_mode_t mode = O_RDONLY;

  status = mdb_env_open(mdb_env, _database_name.null_terminated_chars(), flags, mode);
  if (status != 0) {
    cerr << "CoreReplacement::OpenDatabase:cannot open environment '" << _database_name << " status " << status << '\n';
    return 0;
  }

  return 1;
}

int
CoreReplacement::Initialise(Command_Line& cl) {
  _verbose = cl.option_count('v');

  if (cl.option_present('c')) {
    _remove_chirality = 1;
    if (_verbose) {
      cerr << "Will remove chirality from input molecules\n";
    }
  }

  if (cl.option_present('g')) {
    if (! _chemical_standardisation.construct_from_command_line(cl, _verbose, 'g')) {
      cerr << "Cannot initialise chemical standardisation\n";
      return 0;
    }
  }

  if (cl.option_present('l')) {
    _reduce_to_largest_fragment = 1;
    if (_verbose) {
      cerr << "Will reduce molecules to largest fragment\n";
    }
  }

  if (! cl.option_present('d')) {
    cerr << "Must specify database name via the -d option\n";
    return 0;
  }

  _database_name = cl.string_value('d');

  if (cl.option_present('q')) {
    if (! process_queries(cl, _queries, _verbose, 'q')) {
      cerr << "CoreReplacement::Initialise:cannot read queries (-q)\n";
      return 0;
    }
  }

  if (cl.option_present('s')) {
    const_IWSubstring smarts;
    for (int i = 0; cl.value('s', smarts, i); ++i) {
      std::unique_ptr<Substructure_Hit_Statistics> qry;
      if (! qry->create_from_smarts(smarts)) {
        cerr << "CoreReplacement::Initialise:cannot parse smarts '" << smarts << "'\n";
        return 0;
      }
      _queries << qry.release();
    }
  }

  if (_verbose) {
    cerr << "Definied " << _queries.size() << " queries\n";
  }

  if (_queries.empty()) {
    cerr << "CoreReplacement::Initialise:must specify one or more queries to replace via the -q and/or -s options\n";
    return 0;
  }

  if (cl.option_present('z')) {
    const_IWSubstring z;
    for (int i = 0; cl.value('z', z, i); ++i) {
      if (z == 'i') {
        _ignore_molecules_not_matching_queries = 1;
      } else if (z == 'w') {
        _write_molecules_not_matching_queries = 1;
      } else {
        cerr << "Unrecognised -z qualifier '" << z << "'\n";
        return 0;
      }
    }
  }

  if (! cl.option_present('w')) {
    cerr << "Must specify number of bonds to break via the -w option\n";
    return 0;
  } else {  
    if (! cl.value('w', _bonds_to_break) || _bonds_to_break < 2) {
      cerr << "The number of bonds to break must be at least 2\n";
    }
    if (_verbose) {
      cerr << "Will break  " << _bonds_to_break << " bonds\n";
    }
  }

  if (1 == cl.number_elements() && 0 == strcmp("-", cl[0])) { // reading a pipe, assume smiles
    _input_type = FILE_TYPE_SMI;
  } else if (!all_files_recognised_by_suffix(cl)) {
    cerr << "Cannot discern all file types, use the -i option\n";
    return 0;
  } else if (!process_input_type(cl, _input_type)) {
    return 0;
  }

  return OpenDatabase();
}

int
CoreReplacement::Preprocess(Molecule& m) {
  ++_molecules_read;

  if (_reduce_to_largest_fragment) {
    m.reduce_to_largest_fragment_carefully();
  }

  if (_chemical_standardisation.active()) {
    _chemical_standardisation.process(m);
  }

  if (_remove_chirality) {
    m.remove_all_chiral_centres();
  }

  if (m.natoms() == 0) {
    return 0;
  }

  return 1;
}

int
CoreReplacement::Process(Molecule& m,
                         IWString_and_File_Descriptor& output) {
  Molecule_to_Match target(&m);
  Substructure_Results sresults;
  const Set_of_Atoms * matched_atoms = nullptr;
  for (Substructure_Hit_Statistics * q : _queries) {
    const int nhits = q->substructure_search(target, sresults);
    if (nhits == 0) {
      continue;
    }

    for (const Set_of_Atoms * e : sresults.embeddings()) {
      if (e->number_elements() == _bonds_to_break) {
        matched_atoms = e;
        break;
      }
    }
    if (matched_atoms != nullptr) {
      break;
    }
  }

  if (matched_atoms == nullptr) {
    return HandleNoQueryMatch(m, output);
  }

  return Process(m, *e, output);
}

// The matched atoms define atoms that are retained.
// The first task is to identify the atoms that are
// therefore to be removed/replaced.
int
CoreReplacement::Process(Molecule& m,
        const Set_of_Atoms& matched_atoms,
        IWString_and_File_Descriptor& output) {
  assert(matched_atoms.number_elements() == _bonds_to_break);

  const int * matoms = m.natoms();
  std::unique_ptr<int[]> to_be_removed(new_int(matoms));
  if (! IdentifyAtomsToRemove(m, matched_atoms, to_be_removed.get()) {
    ++_cannot_identify_core;
    return 0;
  }

  return 1;
}

int
CoreReplacement::HandleNoQueryMatch(Molecule& m,
                                    IWString_and_File_Descriptor& output) {
  ++_no_query_match;
  if (_ignore_molecules_not_matching_queries) {
    return 1;
  }

  if (_write_molecules_not_matching_queries) {
    output << m.smiles() << ' ' << m.name() << '\n';
    output.write_if_buffer_holds_more_than(8192);
    return 1;
  }

  return 0;
}

int
CoreReplacement::Report(std::ostream& output) const {
  output << "CoreReplacement:read " << _molecules_read << " molecules\n";
  if (_molecules_read == 0) {
    return 1;
  }

  output << _no_query_match << " molecules did not match any of " << _queries.size() << " queries\n";
  output << _cannot_identify_core << " could not identify core atoms (likely ring)\n";

  return 1;
}

int
ReplaceCore(CoreReplacement& core_replacement,
            Molecule& m,
            IWString_and_File_Descriptor& output) {
  return core_replacement.Process(m, output);
}

int
ReplaceCore(CoreReplacement& core_replacement,
            data_source_and_type<Molecule>& input,
            IWString_and_File_Descriptor& output) {
  Molecule * m;
  while ((m = input.next_molecule()) != nullptr) {
    std::unique_ptr<Molecule> free_m(m);

    if (! core_replacement.Preprocess(*m)) {
      return 0;
    }

    if (! ReplaceCore(core_replacement, *m, output)) {
      return 0;
    }
  }

  return 1;
}

int
ReplaceCore(CoreReplacement& core_replacement,
            const char * fname,
            IWString_and_File_Descriptor& output) {
  FileType input_type = core_replacement.input_type();
  if (input_type == FILE_TYPE_INVALID) {
    input_type = discern_file_type_from_name(fname);
  }

  data_source_and_type<Molecule> input(input_type, fname);
  if (! input.ok()) {
    cerr << "Cannot open '" << fname << "'\n";
    return 0;
  }

  return ReplaceCore(core_replacement, input, output);
}

int
Main(int argc, char** argv) {
  Command_Line cl(argc, argv, "vE:A:i:g:lcd:q:s:w:z:");
  if (cl.unrecognised_options_encountered()) {
    cerr << "unrecognised_options_encountered\n";
    Usage(1);
  }

  const int verbose = cl.option_count('v');

  if (! process_standard_aromaticity_options(cl, verbose, 'A')) {
    cerr << "Cannot process aromaticity options\n";
    return 1;
  }

  if (! process_elements(cl, verbose, 'E')) {
    cerr << "Cannot process standard elements options (-E)\n";
    return 1;
  }

  CoreReplacement core_replacement;
  if (! core_replacement.Initialise(cl)) {
    cerr << "Cannot initialise options\n";
    Usage(1);
  }

  if (cl.empty()) {
    cerr << "Insufficient arguments\n";
    Usage(1);
  }

  IWString_and_File_Descriptor output(1);
  for (const char* fname : cl) {
    if (! ReplaceCore(core_replacement, fname, output)) {
      cerr << "Fatal error processing '" << fname << "'\n";
      return 1;
    }
  }

  if (verbose) {
    core_replacement.Report(cerr);
  }

  return 0;
}

}  // namespace separated_atoms

int
main(int argc, char** argv) {
  int rc = separated_atoms::Main(argc, argv);

  return rc;
}
