cc_library(
    name = "string_data_source",
    visibility = ["//visibility:public"],
    srcs = [
        "iwstring_string_data_source.cc",
    ],
    hdrs = [
        "iwstring_string_data_source.h",
    ],
    deps = [
        "//Foundational/iwaray:iwaray",
        "//Foundational/iwstring:iwstring",
        "@re2//:re2",
    ],
)
