cc_library(
    name = "iwrandom",
    visibility = ["//visibility:public"],
    srcs = [
        "iwrandom.cc",
        "mtrand.cc",
        "normal_distribution.cc",
    ],
    hdrs = [
        "iwrandom.h",
        "mtrand.h",
    ],
    deps = [
        "//Foundational/iwmisc:iwmisc",
    ],
)
