# Convert a .model file generated by svm_learn to a proto

require 'protobuf'
require_relative "lib/iwcmdline.rb"
require_relative "lib/svm_lite_model_pb.rb"

cl = IWCmdline.new("-v")

def to_proto(lines)
  result = SvmLiteModel::SvmLiteModel.new()
  ndx = to_proto
  loop do
  end
  lines.each do |line|
  end
end

lines = []
ARGF.each do |line|
  lines.push(line.chomp)
end

to_proto(lines)
